// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// This file is generated by genversion.mjs. Do not edit it directly.

<<<<<<< HEAD
export const PACKAGE_VERSION = '1.26.1';
=======
export const PACKAGE_VERSION = '1.25.0';
>>>>>>> 8c21ead (working)
export const TARGETED_RPC_VERSION = '1.47.0';
